### PR TITLE
(WIP) Rebase on jenkins/jenkins-experimental:latest-jdk10-incrementals

### PR DESCRIPTION
**Pull request by gmacario**
**DO NOT MERGE YET!**

See https://github.com/gmacario/easy-jenkins/issues/265

See https://jenkins.io/blog/2018/06/17/running-jenkins-with-java10-11/

### CODE REVIEW

**Comment by gmacario** [comment]
Build failed

Excerpt from http://cc-vm1.solarma.it:9080/blue/organizations/jenkins/easy-jenkins/detail/wip%2Ftry-jenkins-jdk10/1/pipeline

```
[nkins_wip_try-jenkins-jdk10-LZWJBPO5RX33VTB7QQKRHN4GN7PVSSWQXHLPJUZNFGX5S2Y2J2CA] Running shell script

Docker version 18.05.0-ce, build f150324

docker-compose version 1.6.2, build 4d72027

Building myjenkins

Step 1/13 : FROM jenkins/jenkins-experimental:latest-jdk10

latest-jdk10: Pulling from jenkins/jenkins-experimental

Digest: sha256:e090c4f96de8307afa1fe150b3802b26bfb51a1d844712098bff3104e53dc358

Status: Image is up to date for jenkins/jenkins-experimental:latest-jdk10

 ---> 8aeb0bfca603

Step 2/13 : USER root

 ---> Running in 151e40ab5743

Removing intermediate container 151e40ab5743

 ---> a73b110e1670

Step 3/13 : RUN apt-get update -qq && apt-get install -qqy     apt-transport-https     ca-certificates     curl     wget     lxc     iptables     dos2unix     groovy2

 ---> Running in c1e9d8b05876

E: Unable to locate package groovy2

Service 'myjenkins' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -qqy     apt-transport-https     ca-certificates     curl     wget     lxc     iptables     dos2unix     groovy2' returned a non-zero code: 100

script returned exit code 1
```

**Comment by gmacario** [comment]
Discussing the docker build failure over https://gitter.im/jenkinsci/jenkins

**Comment by oleg-nenashev** [comment]
@gmacario IIUC the issue is related to the change in the base Docker image (Java 8 => Java 10) which changed some bundled packages and update sources. So it's not directly related to Jenkins.war changes AFAICT, but it may make sense to report it to jenkinsci/docker

**Comment by gmacario** [comment]
@oleg-nenashev: I sorted out the build issue.

Apparently package "groovy2" is now simply called "groovy" - see https://github.com/gmacario/easy-jenkins/pull/266/commits/227673d2b7ac1777e15eca2145ed9df47bb85a1a

However I am not sure whether/where I should report this upstream, since more than an issue in the jenkins Docker image it looks more like a change in the Docker base image

**Comment by oleg-nenashev** [comment]
Then we can keep it as is

**Comment by gmacario** [comment]
Testing branch `wip/try-jenkins-jdk10` on my Windows 7 laptop

```
gpmacario@HW2457:~/github/gmacario/easy-jenkins (wip/try-jenkins-jdk10)$ git log --oneline -1
227673d (HEAD -> wip/try-jenkins-jdk10, origin/wip/try-jenkins-jdk10) Install package "groovy"
gpmacario@HW2457:~/github/gmacario/easy-jenkins (wip/try-jenkins-jdk10)$ ./runme.sh
No active host found
INFO: Creating VirtualBox VM easy-jenkins (cpu:2, memory:2048 MB, disk:50000 MB)
Running pre-create checks...
Creating machine...
(easy-jenkins) Copying C:\Users\GPMacario\.docker\machine\cache\boot2docker.iso to C:\Users\GPMacario\.docker\machine\machines\easy-jenkins\boot2docker.iso...
(easy-jenkins) Creating VirtualBox VM...
(easy-jenkins) Creating SSH key...
...
TODO
```

**Comment by gmacario** [comment]
Closing PR in favour of new PR #270

**Pull request closed without merging**
